[package]
name = "libsovtoken"
version = "0.1.0"
authors = [
  "Matt Raffel <matt.raffel@evernym.com",
  "Stephen Felt <stephen.felt@evernym.com",
  "Cam Parra <camilo.parra@evernym.com",
  "Darien Hess <darien.hess@evernym.com>"
  ]

description = "Payment handler for Sovrin tokens in libindy"


[dependencies]
indy = { git = "https://github.com/hyperledger/indy-sdk.git" }
libc = "0.2.21"
rand = "0.4.2"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
sha2 = "0.6.0"
sha3 = "0.6.0"
sodiumoxide = {version = "0.0.14"}

[lib]
name = "sovtoken"
path = "src/lib.rs"
crate-type = ["rlib", "dylib"]
